sonar.projectKey=AdityaApte145_DevSecOps-Assignment2-Backend
sonar.organization=adityaapte145
sonar.projectName=Frontend LMS

sonar.sources=src
sonar.tests=src/__tests__

sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
